language: go
sudo: required
dist: bionic

go_import_path: go.aporeto.io/trireme-lib

matrix:
  include:
  - go: "1.13.x"
    env: LINT_VERSION="@v1.21.0"
  - go: master
    env: LINT_VERSION="@v1.21.0"
  allow_failures:
  - go: master
  fast_finish: true

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

addons:
   apt:
     packages:
       - libnetfilter-queue-dev
       - libnetfilter-log-dev
       - iptables
       - ipset

env:
  global:
    - TOOLS_CMD=golang.org/x/tools/cmd
    - PATH=$GOROOT/bin:$PATH
    - SUDO_PERMITTED=1
    - GO111MODULE=auto
    - GOLINT_GOGC=75
    - GOGC=75

before_install:
  # we move the go.mod file away so that the next two go gets don't modify the
  # go.mod file for trireme-lib. (otherwise the "git diff" below will fail. We also must
  # get go-diff@v0.5.1 or else go1.11.x will pull in a broken v0.5.0
  - GET_TMP="/tmp/go.get.tmp"
  - mkdir "$GET_TMP"
  - cp go.mod go.sum "$GET_TMP"
  - OLD_DIR="$PWD" ; cd "$GET_TMP"
  - go get github.com/sourcegraph/go-diff@v0.5.1
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint${LINT_VERSION}
  - cd "$OLD_DIR"

install:
  - go mod download
  - git diff --exit-code go.mod go.sum
  - go list -m all || true

script:
  - ./scripts/lint.sh
  - ./scripts/test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
