language: go
sudo: required
dist: trusty

go_import_path: go.aporeto.io/trireme-lib

matrix:
  include:
  - go: "1.11.x"
    env: LINT_VERSION="@v1.16.0" GO111MODULE=auto GODIFF_VERSION="@v0.5.0"
  - go: "1.12.x"
    env: LINT_VERSION="@v1.17.1" GO111MODULE=on GODIFF_VERSION="@v0.5.1"
  - go: "1.13.x"
    env: LINT_VERSION="@v1.21.0" GO111MODULE=on GODIFF_VERSION="@v0.5.1"
  - go: master
    env: LINT_VERSION="@v1.21.0" GO111MODULE=on GODIFF_VERSION="@v0.5.1"
  allow_failures:
  - go: master
  - go: "1.11.x"
  fast_finish: true

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

addons:
   apt:
     packages:
       - libnetfilter-queue-dev
       - libnetfilter-log-dev
       - iptables
       - ipset

env:
  global:
    - TOOLS_CMD=golang.org/x/tools/cmd
    - PATH=$GOROOT/bin:$PATH
    - SUDO_PERMITTED=1
    - GOLINT_GOGC=75
    - GOGC=75

before_install:
  # do this in a tempdir so as not to update the go.mod file in the trireme root dir
  - dir=$(mktemp -d)
  - cp go.mod $dir
  - old=$PWD; cd $dir
  - go get github.com/sourcegraph/go-diff${GODIFF_VERSION}
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint${LINT_VERSION}
  - cd $old

install:
  - go list -m all || true

script:
  - ./.test.sh
  - golangci-lint run --deadline=10m --disable-all --exclude-use-default=false --enable=errcheck --enable=goimports --enable=ineffassign --enable=govet --enable=golint --enable=unused --enable=structcheck --enable=varcheck --enable=deadcode --enable=unconvert --enable=goconst --enable=gosimple --enable=misspell --enable=staticcheck --enable=unparam --enable=prealloc --enable=nakedret --enable=gofmt --enable=typecheck ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
