required = ["github.com/docker/distribution"]

[[constraint]]
  branch = "go-mod"
  name = "github.com/aporeto-inc/go-ipset"

[[constraint]]
  name = "github.com/docker/docker"
  version = "19.03"
  source = "github.com/docker/engine"

[[constraint]]
  name = "github.com/docker/distribution"
  version = "2.7.1"

[[override]]
  name = "github.com/ti-mo/netfilter"
  version = "=0.3.0"

# as per github.com/ti-mo/netfilter go.mod file
[[constraint]]
  name = "github.com/mdlayher/netlink"
  revision = "a1644773bc99cfd147417f646434a663b5892505"

[[constraint]]
  name = "github.com/envoyproxy/go-control-plane"
  version = "v0.9.0"

[[constraint]]
  name = "github.com/aporeto-inc/oxy"
  branch = "go-mod"

[[constraint]]
  name = "go.aporeto.io/netlink-go"
  branch = "master"

[[constraint]]
  name = "go.aporeto.io/tg"
  branch = "master"

[[constraint]]
  #revision = "4fc53a81fb7c994640722ac585fa9ca548971871"
  revision = "ccb5efd37fb7c86364786e9137e22948751de7ed"
  name = "github.com/opencontainers/runc"

[prune]
  go-tests = true
  unused-packages = true
