##
## Aporeto 
## 
[[override]]
  name = "github.com/bvandewalle/go-ipset"
  revision = "0ee897a6d8bc6095299e9c03293ece091ef871de"

##
## 3rd Party
##
[[constraint]]
  name = "github.com/docker/docker"
  version = "v17.05.0-ce-rc3"

## Overriding docker/distribution based on docker/docker/vendor.conf contents. Without this, linters/compilation doesnt work.
[[override]]
  name = "github.com/docker/distribution"
  revision = "b38e5838b7b2f2ad48e06ec4b500011976080621"

[[constraint]]
  name = "go.uber.org/zap"
  version = "^1.5.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.0"

[[override]]
  name = "k8s.io/client-go"
  version = "^7.0.0"

[[override]]
  name = "github.com/json-iterator/go"
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "e386b2658ed20923da8cc9250e552f082899a1ee"

##
## Prunes
##
[prune]
  go-tests = true
  unused-packages = true